"""no mezclar con en categorias

Revision ID: 206f511ee1f3
Revises: 46f3e8788bd2
Create Date: 2026-08-13 05:17:44.233909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206f511ee1f3'
down_revision: Union[str, Sequence[str], None] = '46f3e8788bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias_ulima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_mezclar_con', sa.String(length=300), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias_ulima', schema=None) as batch_op:
        batch_op.drop_column('no_mezclar_con')

    # ### end Alembic commands ###
