"""esquema inicial 3fn

Revision ID: 46f3e8788bd2
Revises: 
Create Date: 2026-08-12 23:23:37.710090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f3e8788bd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_ulima',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('caracteristica_principal', sa.String(length=50), nullable=False),
    sa.Column('clase_sunat', sa.String(length=150), nullable=False),
    sa.Column('clase_basilea', sa.String(length=50), nullable=False),
    sa.Column('grupo_compatibilidad', sa.String(length=50), nullable=False),
    sa.Column('envase_recomendado', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias_ulima'))
    )
    with op.batch_alter_table('categorias_ulima', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_ulima_grupo_compatibilidad'), ['grupo_compatibilidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_categorias_ulima_id'), ['id'], unique=False)

    op.create_table('dependencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependencias')),
    sa.UniqueConstraint('nombre', name=op.f('uq_dependencias_nombre'))
    )
    with op.batch_alter_table('dependencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependencias_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_dependencias_id'), ['id'], unique=False)

    op.create_table('reglas_incompatibilidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grupo_a', sa.String(length=50), nullable=False),
    sa.Column('grupo_b', sa.String(length=50), nullable=False),
    sa.Column('veredicto', sa.String(length=20), nullable=False),
    sa.Column('explicacion_riesgo', sa.Text(), nullable=False),
    sa.CheckConstraint("veredicto IN ('NUNCA', 'SEGREGAR', 'COMPATIBLE')", name=op.f('ck_reglas_incompatibilidad_veredicto_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reglas_incompatibilidad')),
    sa.UniqueConstraint('grupo_a', 'grupo_b', name=op.f('uq_reglas_incompatibilidad_grupo_a_grupo_b'))
    )
    with op.batch_alter_table('reglas_incompatibilidad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reglas_incompatibilidad_grupo_a'), ['grupo_a'], unique=False)
        batch_op.create_index(batch_op.f('ix_reglas_incompatibilidad_grupo_b'), ['grupo_b'], unique=False)
        batch_op.create_index(batch_op.f('ix_reglas_incompatibilidad_id'), ['id'], unique=False)

    op.create_table('laboratorios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('dependencia_id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('responsable_defecto', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['dependencia_id'], ['dependencias.id'], name=op.f('fk_laboratorios_dependencia_id_dependencias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_laboratorios')),
    sa.UniqueConstraint('dependencia_id', 'nombre', name=op.f('uq_laboratorios_dependencia_id_nombre'))
    )
    with op.batch_alter_table('laboratorios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laboratorios_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_laboratorios_dependencia_id'), ['dependencia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_laboratorios_id'), ['id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('ACTIVO', 'INACTIVO')", name=op.f('ck_usuarios_estado_valido')),
    sa.CheckConstraint("rol IN ('investigador', 'laboratorista', 'csbqr_admin')", name=op.f('ck_usuarios_rol_valido')),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], name=op.f('fk_usuarios_laboratorio_id_laboratorios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_laboratorio_id'), ['laboratorio_id'], unique=False)

    op.create_table('declaraciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_residuo', sa.String(length=50), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.String(length=50), nullable=False),
    sa.Column('actividad', sa.String(length=200), nullable=False),
    sa.Column('origen', sa.String(length=50), nullable=False),
    sa.Column('responsable', sa.String(length=100), nullable=False),
    sa.Column('elaborado_por', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=300), nullable=False),
    sa.Column('estado_fisico', sa.String(length=50), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('peso_bruto_g', sa.Float(), nullable=False),
    sa.Column('tara_g', sa.Float(), nullable=False),
    sa.Column('peso_neto_g', sa.Float(), nullable=False),
    sa.Column('peso_neto_kg', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('es_punzocortante', sa.Boolean(), nullable=False),
    sa.Column('es_biologico', sa.Boolean(), nullable=False),
    sa.Column('es_aerosol', sa.Boolean(), nullable=False),
    sa.Column('es_envase_vacio', sa.Boolean(), nullable=False),
    sa.Column('desconocido', sa.Boolean(), nullable=False),
    sa.Column('confianza', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('escalar_csbqr', sa.Boolean(), nullable=False),
    sa.Column('narrativa', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("confianza IN ('Alto', 'Medio', 'Bajo')", name=op.f('ck_declaraciones_confianza_valida')),
    sa.CheckConstraint("estado IN ('GENERADO', 'EN_TRASLADO', 'ALMACENADO', 'DISPUESTO', 'EN_EVALUACION')", name=op.f('ck_declaraciones_estado_valido')),
    sa.CheckConstraint("estado_fisico IN ('Líquido', 'Sólido', 'Gel / Lodo')", name=op.f('ck_declaraciones_estado_fisico_valido')),
    sa.CheckConstraint("origen IN ('Académico', 'Proyecto')", name=op.f('ck_declaraciones_origen_valido')),
    sa.CheckConstraint('peso_bruto_g >= 0', name=op.f('ck_declaraciones_peso_bruto_no_negativo')),
    sa.CheckConstraint('peso_neto_g >= 0', name=op.f('ck_declaraciones_peso_neto_no_negativo')),
    sa.CheckConstraint('peso_neto_kg * 1000 BETWEEN peso_neto_g - 1 AND peso_neto_g + 1', name=op.f('ck_declaraciones_peso_neto_kg_coherente')),
    sa.CheckConstraint('peso_neto_kg >= 0', name=op.f('ck_declaraciones_peso_neto_kg_no_negativo')),
    sa.CheckConstraint('ph IS NULL OR (ph >= 0 AND ph <= 14)', name=op.f('ck_declaraciones_ph_en_rango')),
    sa.CheckConstraint('tara_g >= 0', name=op.f('ck_declaraciones_tara_no_negativa')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_ulima.id'], name=op.f('fk_declaraciones_categoria_id_categorias_ulima')),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorios.id'], name=op.f('fk_declaraciones_laboratorio_id_laboratorios')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_declaraciones_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_declaraciones'))
    )
    with op.batch_alter_table('declaraciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_declaraciones_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaraciones_codigo_residuo'), ['codigo_residuo'], unique=True)
        batch_op.create_index('ix_declaraciones_escalar_csbqr', ['escalar_csbqr'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaraciones_fecha'), ['fecha'], unique=False)
        batch_op.create_index('ix_declaraciones_fecha_estado', ['fecha', 'estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaraciones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaraciones_laboratorio_id'), ['laboratorio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaraciones_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('declaracion_insumos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('declaracion_id', sa.Integer(), nullable=False),
    sa.Column('nombre_quimico', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['declaracion_id'], ['declaraciones.id'], name=op.f('fk_declaracion_insumos_declaracion_id_declaraciones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_declaracion_insumos')),
    sa.UniqueConstraint('declaracion_id', 'nombre_quimico', name=op.f('uq_declaracion_insumos_declaracion_id_nombre_quimico'))
    )
    with op.batch_alter_table('declaracion_insumos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_declaracion_insumos_declaracion_id'), ['declaracion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaracion_insumos_id'), ['id'], unique=False)

    op.create_table('declaracion_observaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('declaracion_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['declaracion_id'], ['declaraciones.id'], name=op.f('fk_declaracion_observaciones_declaracion_id_declaraciones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_declaracion_observaciones')),
    sa.UniqueConstraint('declaracion_id', 'texto', name=op.f('uq_declaracion_observaciones_declaracion_id_texto'))
    )
    with op.batch_alter_table('declaracion_observaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_declaracion_observaciones_declaracion_id'), ['declaracion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaracion_observaciones_id'), ['id'], unique=False)

    op.create_table('declaracion_pictogramas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('declaracion_id', sa.Integer(), nullable=False),
    sa.Column('codigo_pictograma', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['declaracion_id'], ['declaraciones.id'], name=op.f('fk_declaracion_pictogramas_declaracion_id_declaraciones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_declaracion_pictogramas')),
    sa.UniqueConstraint('declaracion_id', 'codigo_pictograma', name=op.f('uq_declaracion_pictogramas_declaracion_id_codigo_pictograma'))
    )
    with op.batch_alter_table('declaracion_pictogramas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_declaracion_pictogramas_declaracion_id'), ['declaracion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaracion_pictogramas_id'), ['id'], unique=False)

    op.create_table('movimientos_kardex',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('declaracion_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=False),
    sa.Column('cantidad_g', sa.Float(), nullable=False),
    sa.Column('laboratorio_origen_id', sa.Integer(), nullable=True),
    sa.Column('laboratorio_destino_id', sa.Integer(), nullable=True),
    sa.Column('registrado_por', sa.String(length=100), nullable=False),
    sa.Column('registrado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.CheckConstraint("motivo IN ('generacion_laboratorio', 'traslado_acopio', 'entrega_eors', 'censo_inicial', 'correccion')", name=op.f('ck_movimientos_kardex_motivo_valido')),
    sa.CheckConstraint("tipo_movimiento IN ('ENTRADA', 'SALIDA', 'TRANSFERENCIA', 'AJUSTE')", name=op.f('ck_movimientos_kardex_tipo_valido')),
    sa.CheckConstraint('cantidad_g >= 0', name=op.f('ck_movimientos_kardex_cantidad_no_negativa')),
    sa.ForeignKeyConstraint(['declaracion_id'], ['declaraciones.id'], name=op.f('fk_movimientos_kardex_declaracion_id_declaraciones'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['laboratorio_destino_id'], ['laboratorios.id'], name=op.f('fk_movimientos_kardex_laboratorio_destino_id_laboratorios')),
    sa.ForeignKeyConstraint(['laboratorio_origen_id'], ['laboratorios.id'], name=op.f('fk_movimientos_kardex_laboratorio_origen_id_laboratorios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimientos_kardex'))
    )
    with op.batch_alter_table('movimientos_kardex', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_kardex_declaracion_id'), ['declaracion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_kardex_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_kardex_registrado_en'), ['registrado_en'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos_kardex', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_kardex_registrado_en'))
        batch_op.drop_index(batch_op.f('ix_movimientos_kardex_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_kardex_declaracion_id'))

    op.drop_table('movimientos_kardex')
    with op.batch_alter_table('declaracion_pictogramas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_declaracion_pictogramas_id'))
        batch_op.drop_index(batch_op.f('ix_declaracion_pictogramas_declaracion_id'))

    op.drop_table('declaracion_pictogramas')
    with op.batch_alter_table('declaracion_observaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_declaracion_observaciones_id'))
        batch_op.drop_index(batch_op.f('ix_declaracion_observaciones_declaracion_id'))

    op.drop_table('declaracion_observaciones')
    with op.batch_alter_table('declaracion_insumos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_declaracion_insumos_id'))
        batch_op.drop_index(batch_op.f('ix_declaracion_insumos_declaracion_id'))

    op.drop_table('declaracion_insumos')
    with op.batch_alter_table('declaraciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_declaraciones_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_declaraciones_laboratorio_id'))
        batch_op.drop_index(batch_op.f('ix_declaraciones_id'))
        batch_op.drop_index('ix_declaraciones_fecha_estado')
        batch_op.drop_index(batch_op.f('ix_declaraciones_fecha'))
        batch_op.drop_index('ix_declaraciones_escalar_csbqr')
        batch_op.drop_index(batch_op.f('ix_declaraciones_codigo_residuo'))
        batch_op.drop_index(batch_op.f('ix_declaraciones_categoria_id'))

    op.drop_table('declaraciones')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_laboratorio_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('laboratorios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laboratorios_id'))
        batch_op.drop_index(batch_op.f('ix_laboratorios_dependencia_id'))
        batch_op.drop_index(batch_op.f('ix_laboratorios_codigo'))

    op.drop_table('laboratorios')
    with op.batch_alter_table('reglas_incompatibilidad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reglas_incompatibilidad_id'))
        batch_op.drop_index(batch_op.f('ix_reglas_incompatibilidad_grupo_b'))
        batch_op.drop_index(batch_op.f('ix_reglas_incompatibilidad_grupo_a'))

    op.drop_table('reglas_incompatibilidad')
    with op.batch_alter_table('dependencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependencias_id'))
        batch_op.drop_index(batch_op.f('ix_dependencias_codigo'))

    op.drop_table('dependencias')
    with op.batch_alter_table('categorias_ulima', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_ulima_id'))
        batch_op.drop_index(batch_op.f('ix_categorias_ulima_grupo_compatibilidad'))

    op.drop_table('categorias_ulima')
    # ### end Alembic commands ###
