"""Captura móvil completa: padrón, envase, dimensiones y propuesta confirmable.

Lo que añade la Fase 9 al esquema:

- `personal` y `personal_alias`: el padrón que sustituye al texto libre de los
  formularios. Los alias son necesarios porque la misma persona se escribió de
  varias maneras en las 856 filas del histórico.
- Envase y dimensiones en `declaraciones`: la página 2 del formato oficial es
  una tabla de fotos de envase con sus medidas, y esos campos se perdían.
- La clasificación pasa a ser una propuesta confirmable: se conserva qué
  propuso el sistema (`categoria_propuesta_id`) aparte de qué quedó vigente.

Revision ID: 7c573c1e4bbb
Revises: e297c62ff9d0
Create Date: 2026-08-13 16:01:16.472623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c573c1e4bbb'
down_revision: Union[str, Sequence[str], None] = 'e297c62ff9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nombre_clave', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('dependencia_id', sa.Integer(), nullable=True),
    sa.Column('es_encargado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('es_csbqr', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('es_generador', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('en_catalogo_oficial', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['dependencia_id'], ['dependencias.id'], name=op.f('fk_personal_dependencia_id_dependencias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal'))
    )
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_personal_dependencia_id'), ['dependencia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_nombre_clave'), ['nombre_clave'], unique=True)

    op.create_table('personal_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('alias_clave', sa.String(length=150), nullable=False),
    sa.Column('alias_texto', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personal.id'], name=op.f('fk_personal_alias_persona_id_personal'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_alias'))
    )
    with op.batch_alter_table('personal_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_alias_alias_clave'), ['alias_clave'], unique=True)
        batch_op.create_index(batch_op.f('ix_personal_alias_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_alias_persona_id'), ['persona_id'], unique=False)

    # El autogenerador propone además reescribir los `server_default` de
    # `categorias_ulima`. No es un cambio real: es la diferencia de comillas con
    # que SQLite guarda una cadena vacía. Se omite a propósito.

    with op.batch_alter_table('declaraciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_envase_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ancho_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('alto_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profundidad_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('categoria_propuesta_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('clasificacion_confirmada', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('confirmada_por', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('confirmada_en', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_declaraciones_categoria_propuesta_id'), ['categoria_propuesta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaraciones_tipo_envase_id'), ['tipo_envase_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_declaraciones_categoria_propuesta_id_categorias_ulima'), 'categorias_ulima', ['categoria_propuesta_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_declaraciones_tipo_envase_id_tipos_envase'), 'tipos_envase', ['tipo_envase_id'], ['id'])

        # Alembic no compara restricciones CHECK: las tres de dimensiones hay
        # que escribirlas a mano o el modelo diría una cosa y la base otra.
        # Cero no es una medida, y admitirlo dejaría pasar el campo sin llenar
        # disfrazado de dato.
        batch_op.create_check_constraint('ancho_positivo', 'ancho_cm IS NULL OR ancho_cm > 0')
        batch_op.create_check_constraint('alto_positivo', 'alto_cm IS NULL OR alto_cm > 0')
        batch_op.create_check_constraint(
            'profundidad_positiva', 'profundidad_cm IS NULL OR profundidad_cm > 0'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('declaraciones', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_declaraciones_profundidad_positiva'), type_='check')
        batch_op.drop_constraint(op.f('ck_declaraciones_alto_positivo'), type_='check')
        batch_op.drop_constraint(op.f('ck_declaraciones_ancho_positivo'), type_='check')
        batch_op.drop_constraint(batch_op.f('fk_declaraciones_tipo_envase_id_tipos_envase'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_declaraciones_categoria_propuesta_id_categorias_ulima'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_declaraciones_tipo_envase_id'))
        batch_op.drop_index(batch_op.f('ix_declaraciones_categoria_propuesta_id'))
        batch_op.drop_column('confirmada_en')
        batch_op.drop_column('confirmada_por')
        batch_op.drop_column('clasificacion_confirmada')
        batch_op.drop_column('categoria_propuesta_id')
        batch_op.drop_column('profundidad_cm')
        batch_op.drop_column('alto_cm')
        batch_op.drop_column('ancho_cm')
        batch_op.drop_column('tipo_envase_id')

    with op.batch_alter_table('personal_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_alias_persona_id'))
        batch_op.drop_index(batch_op.f('ix_personal_alias_id'))
        batch_op.drop_index(batch_op.f('ix_personal_alias_alias_clave'))

    op.drop_table('personal_alias')
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_nombre_clave'))
        batch_op.drop_index(batch_op.f('ix_personal_id'))
        batch_op.drop_index(batch_op.f('ix_personal_dependencia_id'))
        batch_op.drop_index(batch_op.f('ix_personal_codigo'))

    op.drop_table('personal')
    # ### end Alembic commands ###
