"""catalogos institucionales y vocabulario del formato

Revision ID: c7891e12854f
Revises: e15519e1e993
Create Date: 2026-08-13 11:50:55.858270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7891e12854f'
down_revision: Union[str, Sequence[str], None] = 'e15519e1e993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_envase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipos_envase')),
    sa.UniqueConstraint('nombre', name=op.f('uq_tipos_envase_nombre'))
    )
    with op.batch_alter_table('tipos_envase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipos_envase_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_tipos_envase_id'), ['id'], unique=False)

    with op.batch_alter_table('categorias_ulima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caracteristica_declaracion', sa.String(length=100), server_default='', nullable=False))
        batch_op.alter_column('no_mezclar_con',
               existing_type=sa.VARCHAR(length=300),
               server_default='',
               existing_nullable=False)

    with op.batch_alter_table('dependencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_formato', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('en_catalogo_oficial', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('laboratorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('en_catalogo_oficial', sa.Boolean(), server_default='0', nullable=False))

    # Alembic no compara restricciones CHECK, así que el vocabulario nuevo hay
    # que reescribirlo a mano. "Otros" es un origen válido del formato que 7
    # registros históricos usan; "Gel / Lodo" no existe en el formulario, ni en
    # el formato, ni en ninguno de los 856 registros: solo estaba en la web.
    op.execute("UPDATE declaraciones SET estado_fisico = 'Líquido' WHERE estado_fisico = 'Gel / Lodo'")

    with op.batch_alter_table('declaraciones', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_declaraciones_origen_valido'), type_='check')
        batch_op.drop_constraint(op.f('ck_declaraciones_estado_fisico_valido'), type_='check')
        batch_op.create_check_constraint(
            'origen_valido', "origen IN ('Académico', 'Otros', 'Proyecto')")
        batch_op.create_check_constraint(
            'estado_fisico_valido', "estado_fisico IN ('Líquido', 'Sólido')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE declaraciones SET origen = 'Académico' WHERE origen = 'Otros'")

    with op.batch_alter_table('declaraciones', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_declaraciones_origen_valido'), type_='check')
        batch_op.drop_constraint(op.f('ck_declaraciones_estado_fisico_valido'), type_='check')
        batch_op.create_check_constraint(
            'origen_valido', "origen IN ('Académico', 'Proyecto')")
        batch_op.create_check_constraint(
            'estado_fisico_valido', "estado_fisico IN ('Gel / Lodo', 'Líquido', 'Sólido')")

    with op.batch_alter_table('laboratorios', schema=None) as batch_op:
        batch_op.drop_column('en_catalogo_oficial')

    with op.batch_alter_table('dependencias', schema=None) as batch_op:
        batch_op.drop_column('en_catalogo_oficial')
        batch_op.drop_column('token_formato')

    with op.batch_alter_table('categorias_ulima', schema=None) as batch_op:
        batch_op.alter_column('no_mezclar_con',
               existing_type=sa.VARCHAR(length=300),
               server_default=sa.text("('')"),
               existing_nullable=False)
        batch_op.drop_column('caracteristica_declaracion')

    with op.batch_alter_table('tipos_envase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_envase_id'))
        batch_op.drop_index(batch_op.f('ix_tipos_envase_codigo'))

    op.drop_table('tipos_envase')
    # ### end Alembic commands ###
